baseURL = 'https://rohvvn.github.io/cs397_hugo/'
languageCode = 'en-us'
title = 'Pittsburgh Steelers Fan Site'
theme = 'PaperMod'

[params]
  description = 'A fan-made site for the Pittsburgh Steelers â€” team info and favorite players.'

  # PaperMod basics
  defaultTheme = 'auto'
  showReadingTime = true
  showBreadCrumbs = true
  disableThemeToggle = false
  comments = false
  showShareButtons = false

[menu]
  [[menu.main]]
    identifier = 'team'
    name = 'Team Info'
    url = 'team/'
    weight = 1

  [[menu.main]]
    identifier = 'players'
    name = 'Favorite Players'
    url = 'players/'
    weight = 2
